# Generated by Django 5.0.7 on 2024-10-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_naturaldisaster_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='allergies',
            new_name='allergies_reactions',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='injuries',
            new_name='past_injuries_operations',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
