# Generated by Django 5.0.7 on 2024-10-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_incident_alter_userprofile_age_delete_satelliteimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incident',
            new_name='IncidentReport',
        ),
    ]
