# Generated by Django 5.0.7 on 2024-10-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_created_at_incidentreport_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_type', models.CharField(choices=[('theft', 'Theft'), ('vandalism', 'Vandalism'), ('violence', 'Violence'), ('cybercrime', 'Cybercrime')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('media', models.FileField(blank=True, null=True, upload_to='crime_reports/')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
